### ISSUE TITLE
osx-arm64 build

### ISSUE THREAD

**Issue by ivaquero** [conda-forge/r-irkernel-feedstock#27]

**Comment by ivaquero** [comment]
Thank you for your effort!

**Comment by philip-khor** [comment]
No worries! I'll keep this open as it looks like the bot hasn't got to updating this feedstock.

**Comment by philip-khor** [comment]
Ah my bad it's already noarch so there won't be a separate osx-arm64 build. Are you having issues installing r-irkernel on osx-arm64? Dependencies would probably be the issue.

**Comment by ivaquero** [comment]
No, right now, I didn't notice r-irkernel was already noarch. The error was likely raised by r-languageserver. Thank you for the info.
