### ISSUE TITLE
Installing r-irkernel is not sufficient to enable in jupyter lab

### ISSUE THREAD

**Issue by gdevenyi** [conda-forge/r-irkernel-feedstock#30]
### Comment:

The conda installation does not perform step 2 of the installation:
https://irkernel.github.io/installation/

This leads to much confusion.

**Comment by mfansler** [comment]
It's not supposed to auto-register. If you installed from CRAN you would also have to register the kernel. If you want automatic registration, then coinstall `nb_conda_kernels` in the environment with `jupyter`/`jupyterlab`.
