### ISSUE TITLE
Please re-build for R 4.2

### ISSUE THREAD

**Issue by rolweber** [conda-forge/r-irkernel-feedstock#32]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I cannot install r-irkernel alongside r-base 4.2, because the package was only built for r40 and r41.

`conda search --override-channels -c conda-forge "r-irkernel>=1.3"`
```txt
Loading channels: done
# Name                       Version           Build  Channel             
r-irkernel                       1.3   r40hc72bb7e_0  conda-forge         
r-irkernel                       1.3   r41hc72bb7e_0  conda-forge
```

`conda create -n Test --dry-run --override-channels -c conda-forge r-base=4.2.1=*_1 r-irkernel`
```txt
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package r-base conflicts for:
r-base==4.2.1[build=*_1]
r-irkernel -> r-base[version='3.3.2.*|3.4.1.*|>=3.4.1,<3.4.2.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=4.0,<4.1.0a0|>=4.1,<4.2.0a0|>=3.5.1,<3.5.2.0a0']
```

### Installed packages

```shell
not applicable, because I cannot create the conda environment
```

### Environment info

```shell
I'm currently prototyping on linux-64, but will move to linux-ppc64le later.
An r42 build is missing for both platforms.
```

**Comment by dpryan79** [comment]
As far as I know conda-forge hasn't started migrating to 4.2. Once they finally start that all CRAN packages will get rebuilt. 

Xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3200

**Comment by rolweber** [comment]
I see. So there will be a concerted effort. Thanks for pointing that out, I'm new in this area.

**Comment by mfansler** [comment]
This package has now been migrated: https://github.com/conda-forge/r-irkernel-feedstock/pull/33
